spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: ONEpiece20188